{
 "title": "QuickCart Container Monitor - cAdvisor",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (id) (container_last_seen{id=~\"/docker/.*\"}))"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.*\"})"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])) by (id) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.*\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=~\"/docker/.*\"}[1m])) by (id)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}