name: CD - Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./part2-infrastructure/project_folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./part2-infrastructure/project_folder
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/quickcart:latest

      # Scan Image
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/quickcart:latest'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'

      # Deploy
      - name: Deploy to Local Production
        run: |
          echo "Mulai Deployment Aplikasi Go..."
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/quickcart:latest

          docker-compose up -d --no-deps app
          
          docker image prune -f

          echo "Verifikasi Container Berjalan:"
          docker ps --filter "name=quickcart"
          
          echo "✅ Deployment Selesai!"